[phases.setup]
commands = [
  "apt-get update && apt-get install -y ffmpeg",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/bin/yt-dlp",
  "chmod a+rx /usr/bin/yt-dlp"
]

[start]
cmd = "npm start"