[phases.setup]
aptPkgs = ["git", "build-essential", "cmake", "curl", "ffmpeg", "python3", "yt-dlp", "wget"]

[phases.build]
commands = [
  "git clone --depth 1 https://github.com/ggerganov/whisper.cpp.git /app/whisper.cpp",
  "cd /app/whisper.cpp && make"
] 