[phases.setup]
aptPkgs = ["python3", "python3-pip", "ffmpeg", "curl", "yt-dlp"]

[phases.install]
cmds = [
    "cd api && npm ci --only=production"
]

[start]
cmd = "cd api && npm start"

[variables]
NODE_ENV = "production"