name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Menambahkan pemicu manual di sini # Ganti dengan branch utama Anda jika berbeda (misal: master)

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Sesuaikan dengan versi Node.js yang Anda gunakan
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Clean build directory
        run: rm -rf dist

      - name: Build project
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Jika Anda menggunakan custom domain, tambahkan ini:
          # cname: example.com
          # Jika Anda ingin menghapus file .nojekyll (misal untuk Jekyll), tambahkan ini:
          # keep_files: true
